/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AirdropInterface extends ethers.utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "airdrop(address,address[],uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "airdrop",
    values: [string, string[], BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "airdrop", data: BytesLike): Result;

  events: {};
}

export class Airdrop extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AirdropInterface;

  functions: {
    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    airdrop(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "airdrop(address,address[],uint256[],uint256[])"(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  airdrop(
    _nftAddress: string,
    _to: string[],
    _id: BigNumberish[],
    _quantity: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "airdrop(address,address[],uint256[],uint256[])"(
    _nftAddress: string,
    _to: string[],
    _id: BigNumberish[],
    _quantity: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    airdrop(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "airdrop(address,address[],uint256[],uint256[])"(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    airdrop(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "airdrop(address,address[],uint256[],uint256[])"(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    airdrop(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "airdrop(address,address[],uint256[],uint256[])"(
      _nftAddress: string,
      _to: string[],
      _id: BigNumberish[],
      _quantity: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
