/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import { INftUtils } from "./INftUtils";

export class INftUtilsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<INftUtils> {
    return super.deploy(overrides || {}) as Promise<INftUtils>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): INftUtils {
    return super.attach(address) as INftUtils;
  }
  connect(signer: Signer): INftUtilsFactory {
    return super.connect(signer) as INftUtilsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INftUtils {
    return new Contract(address, _abi, signerOrProvider) as INftUtils;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    name: "goatCards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    name: "higherTierCards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    name: "lowerTierCards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061010d806100206000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80636c86eb4514604157806373aff4db14606d578063e2a2d90a146087575b600080fd5b605b60048036036020811015605557600080fd5b503560a1565b60408051918252519081900360200190f35b605b60048036036020811015608157600080fd5b503560b3565b605b60048036036020811015609b57600080fd5b503560c5565b60016020526000908152604090205481565b60006020819052908152604090205481565b6002602052600090815260409020548156fea2646970667358221220a3b7ec0a79f2f77e672dc26ba5be0c733686794b9b7faabaf1ae94b0840d8a1564736f6c634300060c0033";
