/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { ITest } from "./ITest";

export class ITestFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): ITest {
    return new Contract(address, _abi, signerOrProvider) as ITest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_maxSupply",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "_initialSupply",
        type: "uint256"
      },
      {
        internalType: "string",
        name: "_uri",
        type: "string"
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes"
      }
    ],
    name: "create",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
