/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITestInterface extends ethers.utils.Interface {
  functions: {
    "create(uint256,uint256,string,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [BigNumberish, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;

  events: {};
}

export class ITest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITestInterface;

  functions: {
    create(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "create(uint256,uint256,string,bytes)"(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  create(
    _maxSupply: BigNumberish,
    _initialSupply: BigNumberish,
    _uri: string,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "create(uint256,uint256,string,bytes)"(
    _maxSupply: BigNumberish,
    _initialSupply: BigNumberish,
    _uri: string,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    create(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "create(uint256,uint256,string,bytes)"(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    create(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "create(uint256,uint256,string,bytes)"(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "create(uint256,uint256,string,bytes)"(
      _maxSupply: BigNumberish,
      _initialSupply: BigNumberish,
      _uri: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
