/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NftDistributorInterface extends ethers.utils.Interface {
  functions: {
    "distribute(address,address[],uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "distribute",
    values: [string, string[], BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;

  events: {};
}

export class NftDistributor extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NftDistributorInterface;

  functions: {
    distribute(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "distribute(address,address[],uint256[],uint256[])"(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  distribute(
    nft: string,
    to: string[],
    ids: BigNumberish[],
    amounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "distribute(address,address[],uint256[],uint256[])"(
    nft: string,
    to: string[],
    ids: BigNumberish[],
    amounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    distribute(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "distribute(address,address[],uint256[],uint256[])"(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    distribute(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "distribute(address,address[],uint256[],uint256[])"(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    distribute(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "distribute(address,address[],uint256[],uint256[])"(
      nft: string,
      to: string[],
      ids: BigNumberish[],
      amounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
